esphome:
  name: esp32-bluetooth-proxy-a034a0

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

wifi:
  ssid: REDACTED
  password: REDACTED

api:
  reboot_timeout: 0s
  max_send_queue: 32

logger:
  level: DEBUG

ota:
    platform: esphome

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

esp32_ble:
  max_connections: 4

bluetooth_proxy:
  active: true
