import asyncio
from typing import Protocol

from andhrimnir.models import ProbeReading


class TemperatureSource(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def get_current(self) -> ProbeReading: ...
    def subscribe(self) -> asyncio.Queue[ProbeReading]: ...
    def unsubscribe(self, queue: asyncio.Queue[ProbeReading]) -> None: ...
